## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
my_list = [1,2,3]

print (type(my_list))

my_list

<class 'list'>


[1, 2, 3]

In [10]:
arr = np.array(my_list)  #casting the list into an numpy array.

print (type(arr))

arr

<class 'numpy.ndarray'>


array([1, 2, 3])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

print (type(my_matrix))

my_matrix

<class 'list'>


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
mat = np.array(my_matrix)  #casting the list of list (matrix) into an numpy array.

print (type(mat))
mat

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return "evenly" spaced values within a given interval. Those values can be int or float.

In [73]:
np.arange(10)    #if start of array not defined then it is Zero
                #if step size not defined then it is 1.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10)    #excluding 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0.0,10)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [38]:
aran = np.arange(0,11,2.1)   #(start, end, step-size)
aran

array([  0. ,   2.1,   4.2,   6.3,   8.4,  10.5])

### zeros and ones

Generate arrays of zeros or ones in float data type.

In [40]:
a = np.zeros(3)
a

array([ 0.,  0.,  0.])

In [41]:
type(a[1])

numpy.float64

In [63]:
np.zeros((5,5))  #((rows, columns) in tuple) and also notice the two Square brackets incase of 2D array.

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [43]:
np.ones(3)

array([ 1.,  1.,  1.])

In [44]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return "evenly" spaced numbers (not random) over a specified interval. Output will always contain float data type.

In [45]:
np.linspace(0,10,3)    #(start, end, frequency(ie. no. of points))

array([  0.,   5.,  10.])

In [46]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

### Note: 
### linspace takes 3rd argument as frequency while arange takes 3rd arguement as step size. 
### Output of linspace contains float data type only while Output of arange can be int or float data type.


## eye

Creates an identity matrix

In [49]:
np.eye(4)   #it take only integer as its parameter

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a "uniform" distribution
over ``[0, 1)``.

In [87]:
np.random.rand(2)   #1D array . Also float and negative parameters not allowed. Output always float datatype. 

array([ 0.9337644 ,  0.15502615])

In [56]:
np.random.rand(5,5)  #(row, column)

array([[ 0.74445008,  0.16884049,  0.1760933 ,  0.88939878,  0.30434338],
       [ 0.82495358,  0.58991451,  0.67964892,  0.56460572,  0.75954086],
       [ 0.90819916,  0.53924841,  0.27038067,  0.01742139,  0.44057176],
       [ 0.94842869,  0.69678939,  0.65847214,  0.96263544,  0.83192423],
       [ 0.25774579,  0.1243182 ,  0.38712357,  0.60772589,  0.48369099]])

### randn

Return a sample (or samples) from the standard "normal" distribution (centred around zero). Unlike rand which is uniform distribution.

In [61]:
np.random.randn(2)   #float and negative parameters not allowed.

array([-0.00625017, -1.09055431])

In [62]:
np.random.randn(5,5)

array([[ 1.09701441, -0.18243308, -0.75442871, -0.22181601,  1.37747963],
       [-1.23644694, -1.98867741,  0.62483716,  0.64722725, -0.60732977],
       [-1.44858247,  1.12490873,  0.28851734,  0.88758448,  0.23082713],
       [-1.32410698, -1.4711304 , -0.07702857, -0.47214426, -0.22775828],
       [-0.69622256,  0.59918029, -0.64483664, -0.57815251, -1.52647277]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [120]:
np.random.randint(1.5,100)  #start and end can be of int or float data type but output will always be of int datatype.
                            #if start not defined then its Zero.

99

In [85]:
np.random.randint(1,100,10)  #(start, end, frequency)

array([52, 24, 51, 90, 42, 99, 95, 69, 96, 69])

In [119]:
# Alternate way of using random.

from numpy.random import rand, randn, randint

print (rand(2))
print ("\n")
print (randn(2))
print ("\n")
print (randint(2))

[ 0.80244068  0.46381437]


[ 1.17983991  1.37905309]


1


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [70]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
ranarr

array([28,  5, 21, 33,  1, 34, 26, 30, 33, 12])

## Reshape
Returns an array containing the same data with a new shape.

In [96]:
arr.reshape(5,5)  #1D to 2D conversion (row, column)
                    #notice 2 sets of square braces.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [97]:
ranarr

array([28,  5, 21, 33,  1, 34, 26, 30, 33, 12])

In [98]:
ranarr.max()   #max value

34

In [99]:
ranarr.argmax()   #index of max value

5

In [100]:
ranarr.min()

1

In [101]:
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [102]:
# Vector
arr.shape

(25,)

In [106]:
# Notice the two sets of brackets
arr.reshape(1,25)    #(row, column)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [107]:
arr.reshape(1,25).shape

(1, 25)

In [108]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [109]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [110]:
arr.dtype

dtype('int32')